### ISSUE TITLE
Doesn't properly enumerate forest UPN suffixes

### ISSUE THREAD

**Issue by elijsearle** [system32blog/blog#70]
**Describe the bug**
Line 69 $ADForst.UPNSuffixes should read $ADForest.UPNSuffixes

Causes Intune Certificate Connector certs to not be added since they only have our email address domain.

**Comment by RobinBeismann** [comment]
Is your use case NPS Authentication and your UPNs do not match the email address? If so, that is going to be an issue, no matter if the `altSecurityIdentities` attribute is set or not.
Since the update that triggered the need for the OID extension, the UPN needs to be contained at least as SAN attribute, otherwise it won't be able to match the certificate to a user.

**Comment by elijsearle** [comment]
No not NPS authentication.  We are using ADFS authentication. Yes our UPN is in the SAN.  But our UPN is an alias, hence the typo affecting the script properly enumerating our UPN aliases.  Yes we have mapped the altSecurityIdentities since the intune certificate connector doesn’t apply the new OID.  I have manually fixed the script typo and everything is working.

**Comment by RobinBeismann** [comment]
Ah, thanks! I actually didn't even spot the missing `e`, I'll push a pull request later today and get that fixed.

Still curious on how that got in through. I did copy an updated version of the script in after I extended it at work.
